Add cost tracking per LLM to proxy
fastrepl/proxy pull request #3
Opened 2023-09-10 01:17 UTC by ishaan-jaff

Problem: 
It's hard to track how much I have spent when running my proxy. I need to see costs incurred per model on the proxy 

Proposed solution V0:
use `litellm.completion_cost` to track costs per llm 

for each request write costs to costs.json (in a separate thread) [Non-blocking]

Next steps:
- If this looks we can add better tracking for costs + even make a UI dashboard 
Example below:
<img width="1280" alt="Screenshot 2023-07-28 at 5 36 19 PM" src="https://github.com/fastrepl/proxy/assets/29436595/7477eab9-759a-4a41-ae70-0e72d7cca65a">

2023-09-10 01:18 UTC, ishaan-jaff commented on proxy/cost.json
> +{
this is how costs will be tracked per model for v0

2023-09-10 12:55 UTC, yujonglee requested changes
@ishaan-jaff 
Great!

Since `user specific budget` will be added in #4, I think we can slightly modify this to PR to do the following.

1. Remove JSON writing
2. Instead, expose report/reset and report/current (feel free to suggest alternative names).
3. When I send a request to report/reset, the report will be reset (currently, the report only contains the API cost).
4. When I send a request to report/current, I will receive the current report, which includes the cost.

My use-case is to get how much $ is spent for a each evaluation run.

2023-09-10 12:55 UTC, yujonglee commented on proxy/cost.json
> +{
Result looks awesome!

BTW, let's remove this file since it is not part of the code.

2023-09-11 14:06 UTC, yujonglee commented
@ishaan-jaff  Please see https://github.com/fastrepl/proxy/pull/6/commits/92db8de10de0ac0801de4f4a60c7ca7be8e86b12 and share your thought. Only functional difference is remove file read/write. Let me know if you think it is needed.

2023-09-11 14:06 UTC, closed without merging