adding user-specific budgets
fastrepl/proxy pull request #4
Opened 2023-09-10 02:01 UTC by krrishdholakia

Following from our conversation on Discord.

2023-09-10 02:03 UTC, krrishdholakia commented
It seems like i'm failing some ci work? Is there any steps i can take to test and run this locally? @yujonglee

2023-09-10 02:07 UTC, yujonglee commented
@krrishdholakia  run `poetry lock \[--no-update\]` or `task sync` please!

2023-09-10 02:14 UTC, krrishdholakia commented
Ok - sounds good, thanks

2023-09-10 02:25 UTC, krrishdholakia commented
Hmm, Running `poetry lock \[--no-update\]` threw errors for me.

So i ran `poetry lock --no-update` and it still failed.

2023-09-10 02:37 UTC, yujonglee requested changes
@krrishdholakia Sorry for the inconvenience.

Your poetry lock update did pass the install dependency stage, but now it failed on lint stage.

See `Taskfile.yaml`. `lint` and `fmt` should pass.

If you cannot make it to pass lint, you can use `# type: ignore` and move forward. I can handle that later.

2023-09-10 02:37 UTC, yujonglee commented on proxy/main.py
> +    tokens_string = config.get("AUTH_TOKEN", "")
Let's annotate this `: str` to make `mypy` happy

2023-09-10 02:37 UTC, yujonglee commented on proxy/main.py
> +    tokens = tokens_string.split(',') if tokens_string != "" else []
Let's annotate `: str` to make `mypy` happy

2023-09-10 02:46 UTC, krrishdholakia commented
No your fine - i didn't catch that. Thanks for that. I'll run linting before pushing.

2023-09-10 12:41 UTC, yujonglee requested changes

2023-09-10 12:41 UTC, yujonglee commented on proxy/main.py
> +        total_budget = data["total_budget"]
I think we can remove this

2023-09-10 12:41 UTC, yujonglee commented on proxy/main.py
> +    print(f"config: {config}")
We can remove this

2023-09-10 12:41 UTC, yujonglee commented on proxy/main.py
> +        print(f"budget response: {response}")
we can remove this :)

2023-09-10 12:41 UTC, yujonglee commented on proxy/llm.py
> +                raise Exception("No Budget - sorry") # maybe we can raise a 429 rate-limit exception here instead
Yes -  let's raise 429

2023-09-10 15:20 UTC, krrishdholakia commented on proxy/main.py
> +        total_budget = data["total_budget"]
how would you set user-specific budgets? Would it be the same for all? 

I assumed you'd have different tiers (free, paid, etc.)

2023-09-11 14:08 UTC, yujonglee commented
Working on this in #5(https://github.com/fastrepl/proxy/pull/6/commits/9bbfe528fa880f329a1604cf3c52f147e0f0cfbe).

Your initial PR helped me as a reference.

2023-09-11 14:08 UTC, closed without merging